### PR TITLE
Initial Support for TypeScript

### PR DESCRIPTION
**Pull request by deinok**
Notice some important points:
* index.js has been moved inside "src"
* creation of a tsconfig.json
* creation of npm script called "build" -> Compiles TS and creates the bundle
* Added "types" key in package.json
* Added "module" key in package.json

After porting everything to TS we should be able to:
* Expose the lib as an ES2015 module (Node and Browser)
* Generate a version for non ES2015 Node 
* Generate a version for non ES2015 Browsers

If you have any question feel free to ask me anything.

### CODE REVIEW

**Comment by mroloux** [comment]
Thanks! Should we merge this right away, or after you're done with all changes?

**Comment by deinok** [comment]
This gives the basic part of the typescript compiler. So even that its not complete the port now it's mostly just move *.js files to *.ts and fix the issues that typescript detects.

So, yes it can be merged without any issue

**Comment by mroloux** [comment]
Ok, I'll have a look on Friday - out of office tomorrow and the day after.

**Comment by mroloux** [comment]
I'm closing this PR for now. We will probably add proper support for TS at some point in the future.

**Pull request closed without merging**
