### PR TITLE
Add invitation id to invitations list response

### PR DESCRIPTION
**Pull request by nahue**
We need this so we can cancel an invitation using its id

### CODE REVIEW

**Comment by namfal** [comment]
You can also add an assertion for the test case

**Comment by nahue** [comment]
Ok i will!

**Comment by nahue** [comment]
This one needs https://bitbucket.org/seatsio/seatsio-core-v2/pull-requests/1770 to be merged before releasing.

**Comment by mroloux** [comment]
@nahue is this PR still relevant? I assumed we would do this call directly from within our web app.

**Comment by nahue** [comment]
Yes because we still need the invitation id, and this PR adds it to the invitation list response.

**Comment by mroloux** [comment]
Oh ok. I'll approve for now, but the longer-term plan is to move all invitation logic out of the JS client.

**Comment by nahue** [comment]
Yes we agree on that.. but we need the ID to be able to call the cancel API.
Thats why i only added the id without any logic

**Pull request closed without merging**
